esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: ${board}
  framework:
    type: arduino

logger:
  baud_rate: 0

api:
  services:
    - service: arm
      variables:
        area: int
        mode: string
        code: string
      then:
        - lambda: |-
            id(paradox).arm_area(area, mode, code);

    - service: disarm
      variables:
        area: int
        code: string
      then:
        - lambda: |-
            id(paradox).disarm_area(area, code);

external_components:
  - source:
      type: git
      url: ${repo_url}
      ref: ${repo_ref}
    components: [paradox_prt3]
    refresh: 0s

uart:
  id: uart_bus
  tx_pin: ${uart_tx_pin}
  rx_pin: ${uart_rx_pin}
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1

text_sensor:
  - platform: template
    id: paradox_last_message
    name: "Paradox Last Message"

  - platform: template
    id: paradox_alarm_state
    name: "Paradox Alarm State"

  - platform: template
    id: paradox_last_error
    name: "Paradox Last Error"

binary_sensor:
  - platform: template
    id: paradox_zone_1
    name: "Paradox Zone 1"
    device_class: opening

  - platform: template
    id: paradox_zone_2
    name: "Paradox Zone 2"
    device_class: opening

  - platform: template
    id: paradox_zone_3
    name: "Paradox Zone 3"
    device_class: opening

  - platform: template
    id: paradox_zone_4
    name: "Paradox Zone 4"
    device_class: opening

  - platform: template
    id: paradox_zone_5
    name: "Paradox Zone 5"
    device_class: opening

  - platform: template
    id: paradox_zone_6
    name: "Paradox Zone 6"
    device_class: opening

  - platform: template
    id: paradox_zone_7
    name: "Paradox Zone 7"
    device_class: opening

  - platform: template
    id: paradox_zone_8
    name: "Paradox Zone 8"
    device_class: opening

  - platform: template
    id: paradox_zone_9
    name: "Paradox Zone 9"
    device_class: opening

  - platform: template
    id: paradox_zone_10
    name: "Paradox Zone 10"
    device_class: opening

  - platform: template
    id: paradox_zone_11
    name: "Paradox Zone 11"
    device_class: opening

  - platform: template
    id: paradox_zone_12
    name: "Paradox Zone 12"
    device_class: opening

  - platform: template
    id: paradox_zone_13
    name: "Paradox Zone 13"
    device_class: opening

  - platform: template
    id: paradox_zone_14
    name: "Paradox Zone 14"
    device_class: opening

  - platform: template
    id: paradox_zone_15
    name: "Paradox Zone 15"
    device_class: opening

  - platform: template
    id: paradox_zone_16
    name: "Paradox Zone 16"
    device_class: opening

  - platform: template
    id: paradox_zone_17
    name: "Paradox Zone 17"
    device_class: opening

  - platform: template
    id: paradox_zone_18
    name: "Paradox Zone 18"
    device_class: opening

  - platform: template
    id: paradox_zone_19
    name: "Paradox Zone 19"
    device_class: opening

  - platform: template
    id: paradox_zone_20
    name: "Paradox Zone 20"
    device_class: opening

  - platform: template
    id: paradox_zone_21
    name: "Paradox Zone 21"
    device_class: opening

  - platform: template
    id: paradox_zone_22
    name: "Paradox Zone 22"
    device_class: opening

  - platform: template
    id: paradox_zone_23
    name: "Paradox Zone 23"
    device_class: opening

  - platform: template
    id: paradox_zone_24
    name: "Paradox Zone 24"
    device_class: opening

  - platform: template
    id: paradox_zone_25
    name: "Paradox Zone 25"
    device_class: opening

  - platform: template
    id: paradox_zone_26
    name: "Paradox Zone 26"
    device_class: opening

  - platform: template
    id: paradox_zone_27
    name: "Paradox Zone 27"
    device_class: opening

  - platform: template
    id: paradox_zone_28
    name: "Paradox Zone 28"
    device_class: opening

  - platform: template
    id: paradox_zone_29
    name: "Paradox Zone 29"
    device_class: opening

  - platform: template
    id: paradox_zone_30
    name: "Paradox Zone 30"
    device_class: opening

  - platform: template
    id: paradox_zone_31
    name: "Paradox Zone 31"
    device_class: opening

  - platform: template
    id: paradox_zone_32
    name: "Paradox Zone 32"
    device_class: opening

  - platform: template
    id: paradox_zone_33
    name: "Paradox Zone 33"
    device_class: opening

  - platform: template
    id: paradox_zone_34
    name: "Paradox Zone 34"
    device_class: opening

  - platform: template
    id: paradox_zone_35
    name: "Paradox Zone 35"
    device_class: opening

  - platform: template
    id: paradox_zone_36
    name: "Paradox Zone 36"
    device_class: opening

  - platform: template
    id: paradox_zone_37
    name: "Paradox Zone 37"
    device_class: opening

  - platform: template
    id: paradox_zone_38
    name: "Paradox Zone 38"
    device_class: opening

  - platform: template
    id: paradox_zone_39
    name: "Paradox Zone 39"
    device_class: opening

  - platform: template
    id: paradox_zone_40
    name: "Paradox Zone 40"
    device_class: opening

  - platform: template
    id: paradox_ready
    name: "Paradox Area Ready"

  - platform: template
    id: paradox_trouble
    name: "Paradox Trouble"

  - platform: template
    id: paradox_memory
    name: "Paradox Alarm Memory"

  - platform: template
    id: paradox_strobe
    name: "Paradox Strobe"

paradox_prt3:
  id: paradox
  uart_id: uart_bus
  last_message: paradox_last_message
  alarm_state: paradox_alarm_state
  last_error: paradox_last_error

  zones:
    - paradox_zone_1
    - paradox_zone_2
    - paradox_zone_3
    - paradox_zone_4
    - paradox_zone_5
    - paradox_zone_6
    - paradox_zone_7
    - paradox_zone_8
    - paradox_zone_9
    - paradox_zone_10
    - paradox_zone_11
    - paradox_zone_12
    - paradox_zone_13
    - paradox_zone_14
    - paradox_zone_15
    - paradox_zone_16
    - paradox_zone_17
    - paradox_zone_18
    - paradox_zone_19
    - paradox_zone_20
    - paradox_zone_21
    - paradox_zone_22
    - paradox_zone_23
    - paradox_zone_24
    - paradox_zone_25
    - paradox_zone_26
    - paradox_zone_27
    - paradox_zone_28
    - paradox_zone_29
    - paradox_zone_30
    - paradox_zone_31
    - paradox_zone_32
    - paradox_zone_33
    - paradox_zone_34
    - paradox_zone_35
    - paradox_zone_36
    - paradox_zone_37
    - paradox_zone_38
    - paradox_zone_39
    - paradox_zone_40

  ready: paradox_ready
  trouble: paradox_trouble
  memory: paradox_memory
  strobe: paradox_strobe
